name: Create ZIP & Release

on: 
  workflow_dispatch:
    inputs:
      version: 
        description: 'Firmware version'
        default: 'v0.4'
        required: true

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: firmware/
          recursive: true
          dest: klor_kmk_firmware.zip
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "klor_kmk_firmware.zip"
          name: "KLOR KMK Firmware"
          tag: "${{ github.event.inputs.version }}"
          token: ${{ secrets.GITHUB_TOKEN }}
